[package]
name = "AlgosRust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "interface"
path = "src/main.rs"

[lib]
name = "solvers"
path = "src/codinggames/lib.rs"
